package constant

const (
	ENV_AZURE_OPENAI_ENDPOINT     = "AZURE_OPENAI_ENDPOINT"
	ENV_AZURE_OPENAI_API_VER      = "AZURE_OPENAI_API_VER"
	ENV_AZURE_OPENAI_MODEL_MAPPER = "AZURE_OPENAI_MODEL_MAPPER"
	ENV_AZURE_OPENAI_API_KEY      = "AZURE_OPENAI_API_KEY"

	ENV_AZURE_OPENAI_HTTP_PROXY  = "AZURE_OPENAI_HTTP_PROXY"
	ENV_AZURE_OPENAI_SOCKS_PROXY = "AZURE_OPENAI_SOCKS_PROXY"
)
