name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - 'assets/**'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - 'assets/**'
      - '**/*.gitignore'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: false
          go-version-file: go.mod

      - name: Verify gofmt
        run: |
          make fmt && git add azure util cmd constant &&
          git diff --cached --exit-code || (echo 'Please run "make fmt" to verify gofmt' && exit 1);
      - name: Verify govet
        run: |
          make vet && git add azure util cmd constant &&
          git diff --cached --exit-code || (echo 'Please run "make vet" to verify govet' && exit 1);

      - name: Build
        run: make build